In [ ]:
# Demonstrate the SVD algorithm from a small dataset


In [7]:
import pandas as pd
import numpy as np
# https://stevealbertwong.github.io/2016/12/23/SVD/
col = ['hp','dell','macbook','thinbook','notebook','acer']
x =  np.array([
	[1,1,0.5,3,4,5],
	[2,2,1,4,1,4],
	[3,3,1.5,2,5,1],
	[4,4,2,3,4,2],
	[1,3,2.2,1,3,4],
	[5,5,3,4.1,4,3],
	[2,3,3.5,2,5,3],
	[2,1,4,5,4,5]])
data=pd.DataFrame(data=x,columns=col)
data

hp  dell  macbook  thinbook  notebook  acer
0  1.0   1.0      0.5       3.0       4.0   5.0
1  2.0   2.0      1.0       4.0       1.0   4.0
2  3.0   3.0      1.5       2.0       5.0   1.0
3  4.0   4.0      2.0       3.0       4.0   2.0
4  1.0   3.0      2.2       1.0       3.0   4.0
5  5.0   5.0      3.0       4.1       4.0   3.0
6  2.0   3.0      3.5       2.0       5.0   3.0
7  2.0   1.0      4.0       5.0       4.0   5.0

In [15]:
from numpy import array
from scipy.linalg import svd

# https://setosa.io/ev/principal-component-analysis/
U,Sigma ,V_transpose = svd(data,full_matrices=False)
print(f'The covariance of matrix is \n {np.dot(data.T,data)}')
print(f'\nThe U left sigular matrix\n {U}')
print(f'\nThe Sigma diagonal/eigenvalues matrics\n {Sigma}')
print(f'\nThe V the right singular 
\n {V_transpose}')


The covariance of matrix is 
 [[ 64.    66.    47.2   64.5   78.    59.  ]
 [ 66.    74.    51.1   63.5   85.    65.  ]
 [ 47.2   51.1   49.59  56.    70.6   60.3 ]
 [ 64.5   63.5   56.    84.81  87.4   86.3 ]
 [ 78.    85.    70.6   87.4  124.    96.  ]
 [ 59.    65.    60.3   86.3   96.   105.  ]]

The U matric
 [[-0.30590322  0.46316253 -0.21498354 -0.41676554  0.56293951  0.30604689]
 [-0.27375973  0.3219779   0.58649551 -0.24518932 -0.04070518 -0.64312069]
 [-0.31002654 -0.40512123 -0.25544482  0.05767282  0.48944992 -0.38933072]
 [-0.36920974 -0.36799845  0.17093983 -0.0598419   0.12437824  0.14604583]
 [-0.28206969  0.10486739 -0.33252563 -0.50187797 -0.57087259  0.06433179]
 [-0.46222638 -0.35515518  0.41020627 -0.02091146 -0.16715534  0.42150725]
 [-0.36568157 -0.09638941 -0.48623812  0.17400222 -0.26296543 -0.34116687]
 [-0.41485781  0.48563499  0.0079133   0.69042445 -0.05851311  0.14704255]]

The Sigma matrics
 [20.96297659  5.78847089  3.8530503   2.6869039   2.50639837  0

In [26]:
# !pip install apyori
from apyori import apriori
col2 = ['Gender','Height','Weight','output']
url = 'https://raw.githubusercontent.com/ukantjadia/30-days-of-Mahcine-Learning/Main/DAY-22/BMI.csv'
data_bmi = pd.read_csv(url)
data_bmi.columns= col2
association_rule = apriori(data_bmi,min_support=0.50,min_confidence=0.7,min_lift=1.2,min_lenght=2)
# print(list(association_rule))
print(list(association_rule))

[RelationRecord(items=frozenset({'e', 'g'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]), RelationRecord(items=frozenset({'e', 'h'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]), RelationRecord(items=frozenset({'e', 'i'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'i'}), items_add=frozenset({'e'}), confidence=1.0, lift=1.3333333333333333)]), RelationRecord(items=frozenset({'h', 'g'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'g'}), items_add=frozenset({'h'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'h'}), items_add=frozenset({'g'}), confidence=1.0, lift=2.0)]), RelationRecord(items=frozenset({'i', 'g'}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset({'g'}), items_add=