In [2]:
# importing the libraries

import pandas as pd
import numpy as np
import random 
from numpy import random as rnn

# Random Number generation

In [3]:
# rand = random.randint(39,100,5)
print(f' Generating single Random number: {rnn.rand()}')
print(f' \nGenerating list of a Random number with numpy: \n{rnn.rand(10)}')
print(f' \nGenerating 2D arary of Random number \n{rnn.rand(5,5)}')
print(f' \nGenerating 2D arary of with choice Random number: \n{rnn.choice([7,8,1,9],size=(3,5))}')

ran_numpy = rnn.rand(10,5) 


ran_numpy_int = rnn.randint(13,100)
# ran_numpy
# ran_numpy_int


 Generating single Random number: 0.7314256872950725
 
Generating list of a Random number with numpy: 
[0.89583958 0.75025121 0.30967915 0.305292   0.72259752 0.9626228
 0.14583477 0.08222148 0.41748344 0.05409212]
 
Generating 2D arary of Random number 
[[0.15905928 0.96782603 0.96581076 0.15573206 0.95728684]
 [0.60673854 0.49176789 0.23408041 0.80555103 0.55327155]
 [0.84720909 0.6958748  0.45822263 0.76376646 0.13389758]
 [0.81339493 0.64355985 0.20264834 0.7801658  0.47416228]
 [0.48804889 0.69553995 0.66752198 0.44735476 0.15608946]]
 
Generating 2D arary of with choice Random number: 
[[1 1 1 7 9]
 [9 8 1 9 8]
 [7 7 1 1 9]]


---

# Bootstraping 

- Bootstraping gives the Best Utilization of limited data.
## What is Bootstraping sampling?
- It is a method that involves drawing of sample data repeatedly wiht replacement from a data source to estimate a population parameter
### When to use ?
- When the sample data is fairly small(but not tiny)
- When the distribution(dataset) is not clean

In [4]:
x = rnn.randint(0,1000,500)

sample_mean=[]
x_mean=[]

# Bootstrap sampling
for i in range(5):
    y = random.sample(x.tolist(),5)
    avg = np.mean(y)
    
    sample_mean.append(avg)
    
print(sample_mean)
print(np.mean(x))

[333.4, 336.0, 370.4, 489.2, 514.0]
504.708


---

# Covarience 


### What is Covarience 
- Covariance is a measure of the relationship between two random variables and to what extent, they change together.
- it refers to the measure of the directional relationship between two random variables.

### What it tells?
- Covariance indicates the relationship of two variables whenever one variable changes. If an increase in one variable results in an increase in the other variable, both variables are said to have a positive covariance. Decreases in one variable also cause a decrease in the other.

### Covariance Vs Correlation
- Both used in statistics and regression analysis.
- Covariance shows you how the two variables differ, whereas correlation shows you how the two variables are related.

In [5]:
# Generating random dataset for Covarience
a = rnn.randint(0,100,40)
b = rnn.randint(0,100,40)

In [6]:
a_mean = np.mean(a)
b_mean = np.mean(b)
sum =0
for i in range(0, len(a)):
    sum += ((a[i] - a_mean) * (b[i] - b_mean))

print(f' Calculating manually {sum/(len(a)-1)}')

# To verify 

data = {'col1':a,'col2':b}
df = pd.DataFrame(data)
print(f"\nWith pandas: \n{df.cov()}")


print(f"\nWith numpy {np.cov(a, b, bias=False)[1][0]}")

 Calculating manually -8.46923076923075

With pandas: 
            col1        col2
col1  794.558333   -8.469231
col2   -8.469231  669.169231

With numpy -8.46923076923078


---

# Correlation


### What is Correlation
- Correlation is a statistical measure that indicates the extent to which two or more variables fluctuate in relation to each other.
- A correlation is a statistical measure of the relationship between two variables. 
- The measure is best used in variables that demonstrate a linear relationship between each other. 

### Correlation Cofficient 
- The correlation coefficient is a value that indicates the strength of the relationship between variables. 
- The coefficient can take any values from -1 to 1. The interpretations of the values are following-
> -1 :- variables tend to move in opposite directions (i.e., when one variable increases, the other variable decreases). <br/>
> 0 :- The variables do not have a relationship with each other.<br/>
> 1 :- variables tend to move in the same direction (i.e., when one variable increases, the other variable also increases).<br/>

### Formula
![image](https://cdn.corporatefinanceinstitute.com/assets/correlation1.png)
<div align='center'><br/>
> rxy – the correlation coefficient of the linear relationship between the variables x and y<br/>
> xi – the values of the x-variable in a sample<br/>
> x̅ – the mean of the values of the x-variable<br/>
> yi – the values of the y-variable in a sample<br/>
> ȳ – the mean of the values of the y-variable<br/> </div>

In [29]:
# Generating random dataset for Covarience
a = rnn.randint(0,100,10)
b = rnn.randint(0,100,10)
data = {'col1':a,'col2':b}
df = pd.DataFrame(data)


In [30]:
# print(df)
sum_num,sum_dem = 0,0

for i,x in enumerate(df['col1']):
    y = df['col2'][i]
    
    sum_num += ((x - np.mean(a))*(y - np.mean(b)))
    
    sum_dem += (((x - np.mean(a))**2) * (y - np.mean(b))**2)


    
print(f"{sum_num}, {sum_dem}")
    
cor = sum_num / sum_dem**(0.5)
print(cor)
print(df.corr().abs())

1644.0000000000002, 3978309.54
0.8242377999344294
          col1      col2
col1  1.000000  0.214182
col2  0.214182  1.000000
